### ISSUE TITLE
Doesn't work with vulkan mod 

### ISSUE THREAD

**Issue by miggythewriter** [Aeroshide/SpecSpoof#6]
This mod is great but when using vulkan mod it doesn't work like I edit something but It doesn't show up.

**Comment by Aeroshide** [comment]
this is because vulkanmod uses a different rendering engine than vanilla, so they fetch hardware information directly from the vulkan library.

A workaround might be possible by injecting into vulkanmod to fetch data the "SpecSpoof" way, i haven't look deep into this yet, putting this on the TODO tho.

**Comment by Aeroshide** [comment]
implemented as of d392957f1345e0305e720b6c489268e7031a90b0, released on modrinth too. thanks for the suggestion, sorry it took quite long.
